### ISSUE TITLE
Webhook url showing in WP footer

### ISSUE THREAD

**Issue by dblodorn** [lukethacoder/wp-webhook-netlify-deploy#4]
Hey! awesome plugin, I've tried making one of these myself but like the extra features of yours.

One thing that is a little odd is that the build hook url shows up in all admin pages in the footer:

https://static.md/f52fd1d8eca2793001ea779a8675e0ba.png

Any ideas as to why? I am on a multisite installation.

**Comment by lukethacoder** [comment]
Closing as issue was fixed in https://github.com/lukethacoder/wp-webhook-deploy-netlify/commit/6aeaf111ff00253516d531271b8be80978f3eb28

**Comment by kimhornung** [comment]
Please consider reopening this issue. The problem still occurs: the JavaScript is enqueued on all admin pages, not only on the plugin's own admin pages.
